title: Taehwan Kim's resume
description: My online resume.
show_downloads: false

linkedin_url: https://linkedin.com/in/bluezery
github_url: https://github.com/bluezery
email_url: "mailto: ohpowel@gmail.com"

theme: jekyll-theme-cayman